Repository oz-main-10-team1/yours-scently-fe, pull requests merged in 2025-07, with the labels that each got.

#4 chore: 절대경로 설정(SCENTLY-8)
  tsconfig.json
Labels: chore

#6 fix: 빌드 오류 해결(SCENTLY-11)
  package-lock.json
  package.json
Labels: fix

#8 chore: ci github action 추가(SCENTLY-21)
  .github/workflows/build-test.yml
Labels: chore

#9 feat: 아이콘 공통 컴포넌트 구현(SCENTLY-22)
  next.config.ts
  package-lock.json
  package.json
  src/components/ui/Icon.tsx
  src/components/ui/IconButton.tsx
  src/types/svgr.d.ts
  tsconfig.json
Labels: feature

#10 fix: svg file loader 규칙 누락 경고 추가(SCENTLY-28)
  next.config.ts
Labels: fix

#12 feat: tailwind 기본 스타일 적용(SCENYLY-36)
  src/app/globals.css
Labels: feature

#13 feat: 버튼 컴포넌트 구현 (SCENTLY-35)
  src/components/ui/Button.tsx
Labels: feature

#14 feat: footer 구현(SCENTLY-34)
  src/app/layout.tsx
  src/assets/icons/footer/icon-sns-blog.svg
  src/assets/icons/footer/icon-sns-instagram.svg
  src/assets/icons/footer/icon-sns-kakao.svg
  src/assets/icons/footer/icon-sns-youtube.svg
  src/assets/logo/logo-gray.svg
  src/assets/logo/logo-white.svg
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
Labels: feature

#16 refactor: 버튼프롭스 타입 선언 위의 JSDoc 주석 제거(SCENTLY-35)
  src/components/ui/Button.tsx
Labels: refactor
