Repository oz-main-10-team1/yours-scently-fe, pull requests merged in 2025-08, with the labels that each got.

#22 feat: checkbox, radio 공통 컴포넌트 구현(SCENTLY-55)
  src/app/globals.css
  src/components/ui/input/Checkbox.tsx
  src/components/ui/input/Radio.tsx
Labels: feature

#17 feat: input 공통 컴포넌트 구현(SCENTLY-44)
  src/components/ui/input/AuthCodeInput.tsx
  src/components/ui/input/Checkbox.tsx
  src/components/ui/input/Input.tsx
  src/components/ui/input/PhoneInput.tsx
  src/components/ui/input/ValidationMessage.tsx
  src/hooks/useTimer.ts
  src/utils/timeUtils.ts
Labels: feature

#24 feat: 스와이퍼 라이브러리 설치(SCENTLY-71)
  package-lock.json
  package.json
Labels: feature

#20 feat: card 생성(SCENTLY-43)
  public/fallback-image.svg
  src/components/common/Card.tsx
  src/components/common/CartCard.tsx
  src/components/common/Footer.tsx
  src/components/common/ReviewCard.tsx
  src/components/common/ReviewlistCard.tsx
Labels: feature

#25 feat: 메인페이지 레이아웃 및 섹션 구성(SCENTLY-59)
  src/app/page.tsx
  src/assets/images/main-banner-img.png
  src/assets/images/promo-banner-bg-img.png
  src/assets/images/sub-banner-bg-img.png
  src/assets/images/sub-banner-promo-img.png
  src/assets/images/sub-banner-sample-img.png
  src/components/feature/main/BestReviews.tsx
  src/components/feature/main/MainBanner.tsx
  src/components/feature/main/PersonalizedProducts.tsx
  src/components/feature/main/PromoBanner.tsx
  src/components/feature/main/SubBanner.tsx
Labels: feature

#29 feat: my page 구현(SCENTLY-74)
  src/app/my-page/mocks/mockCard.ts
  src/app/my-page/mocks/mockReviewCard.ts
  src/app/my-page/page.tsx
  src/components/common/Card.tsx
  src/components/common/ReviewCard.tsx
  src/components/feature/my-page/MypageCard.tsx
Labels: feature

#32 feat: 이메일 로그인 페이지 및 회원가입 모달 구현(SCENTLY-69)
  src/app/login/@modal/(.)register/page.tsx
  src/app/login/@modal/default.tsx
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/components/common/Modal.tsx
  src/components/ui/Button.tsx
  src/components/ui/input/PhoneInput.tsx
  src/components/ui/tabs/GenderToggle.tsx
Labels: feature

#31 refactor: authCodeInput 컴포넌트 리팩토링(SCENTLY-84)
  src/components/ui/input/AuthCodeInput.tsx
Labels: refactor

#33 fix: mypage 오류 수정(SCENTLY-85)
  src/app/@subModal/(...)my-page-modal/page.tsx
  src/components/feature/my-page/MypageCard.tsx
Labels: fix

#35 refactor: starrating 컴포넌트 리펙토링(SCENTLY-92)
  src/components/ui/tabs/StarRating.tsx
Labels: refactor

#36 feat: 카드 스와이퍼 UI 및 슬라이드 기능 적용(SCENTLY-77)
  src/app/globals.css
  src/app/my-page/mocks/mockCard.ts
  src/app/my-page/mocks/mockReviewCard.ts
  src/app/my-page/page.tsx
  src/components/common/ReviewCard.tsx
  src/components/common/card-component/MainCard.tsx
  src/components/common/card-swiper/CardSwiper.tsx
  src/components/common/review-card/ReviewCard.tsx
  src/components/common/review-swiper/ReviewSwiper.tsx
  src/types/CardSwiper.types.ts
  src/types/MainCard.type.ts
  src/types/ReviewCard.types.ts
  src/types/ReviewSwiper.types.ts
Labels: feature

#39 refactor: 카드 스와이퍼 수정(SCENTLY-99)
  src/app/globals.css
  src/app/my-page/mocks/mockCard.ts
  src/app/my-page/page.tsx
  src/components/common/card-component/MainCard.tsx
  src/components/common/card-swiper/CardSwiper.tsx
  src/types/CardSwiper.types.ts
  src/types/MainCard.type.ts
Labels: refactor

#42 feat: overlay-kit 설치(SCENTLY-103)
  package-lock.json
  package.json
Labels: feature

#40 feat: 설문페이지 ui 구현(SCENTLY-78)
  public/survey/warmVanillaWoods.png
  src/app/survey/page.tsx
  src/components/feature/survey/IntensityQuestion.tsx
  src/components/feature/survey/IntroPage.tsx
  src/components/feature/survey/KeywordsQuestion.tsx
  src/components/feature/survey/OccasionQuestion.tsx
  src/components/feature/survey/RecommendationsPage.tsx
  src/components/feature/survey/ScentMood.tsx
  src/constants/urls.ts
  src/types/Survey.ts
Labels: feature

#43 feat: 회원가입폼 누락된부분 마무리(SCENTLY-101)
  src/api/signup/signup.ts
  src/app/login/@modal/(.)register/actions.ts
  src/app/login/@modal/(.)register/page.tsx
  src/app/login/@modal/(.)register/schema.ts
  src/components/feature/register/BirthDateSection.tsx
  src/components/feature/register/EmailSection.tsx
  src/components/feature/register/GenderSection.tsx
  src/components/feature/register/NameSection.tsx
  src/components/feature/register/NicknameSection.tsx
  src/components/feature/register/PasswordSection.tsx
  src/components/feature/register/PhoneSection.tsx
  src/components/ui/input/PhoneInput.tsx
Labels: feature

#45 feat: 상세페이지 ui 구현(SCENTLY-70)
  public/mock/detail/detail-image.png
  public/mock/detail/detail-main.png
  src/app/detail/[id]/mock/mock.json
  src/app/detail/[id]/page.tsx
  src/components/common/CartItemsList.tsx
  src/components/feature/detail/CartModal.tsx
  src/components/feature/detail/DetailSwiper.tsx
  src/components/feature/detail/ProductActionBar.tsx
  src/components/feature/detail/ProductDetailInfo.tsx
  src/components/ui/input/QuantitySelector.tsx
  src/components/ui/tabs/TabScroll.tsx
  src/constants/urls.ts
  src/hooks/useScroll.ts
Labels: feature

#48 refactor: 카드스와이퍼, 상세페이지 컴포넌트 스와이퍼 수정(SCENTLY-112)
  src/app/detail/[id]/page.tsx
  src/components/common/card-swiper/CardSwiper.tsx
Labels: refactor

#38 feat: 개인정보 컴포넌트 작성(SCENTLY-75)
  src/app/privacy-page/mocks/userMockData.ts
  src/app/privacy-page/page.tsx
  src/components/common/Footer.tsx
  src/components/feature/privacy-page/FieldRow.tsx
  src/components/feature/privacy-page/PrivacyEdit.tsx
  src/components/feature/privacy-page/PrivacyView.tsx
  src/constants/messages.ts
  src/types/user.d.ts
Labels: feature

#49 feat: 이메일 로그인 api 연동(SCENTLY-111)
  src/api/api.ts
  src/api/login/emailLogin.ts
  src/api/signup/checkEmailVerificationCode.ts
  src/api/signup/checkNickname.ts
  src/api/signup/sendEmailVerificationCode.ts
  src/api/signup/signup.ts
  src/app/login/@modal/(.)register/actions.ts
  src/app/login/actions.ts
  src/app/login/page.tsx
  src/app/login/schema.ts
  src/constants/auth.ts
  src/constants/urls.ts
Labels: feature

#50 style: 장바구니 페이지, 상세 페이지 width 수정(SCENTLY-123)
  src/app/cart/page.tsx
  src/app/detail/[id]/page.tsx
  src/components/common/CartItemsList.tsx
  src/components/feature/detail/CartModal.tsx
  src/components/feature/detail/DetailSwiper.tsx
  src/components/feature/detail/ProductActionBar.tsx
Labels: style

#51 feat: 아이디 찾기 모달 구현(SCENTLY-124)
  src/api/account-find/findEmail.ts
  src/app/layout.tsx
  src/app/login/@modal/(.)register/page.tsx
  src/app/login/actions.ts
  src/app/login/page.tsx
  src/app/login/schema.ts
  src/assets/icons/auth/find-email/icon-thumbnail.svg
  src/assets/icons/icon-modal-close.svg
  src/components/common/OverlayProvider.tsx
  src/components/feature/auth/find-id/FindIdForm.tsx
  src/components/feature/auth/find-id/FindIdModal.tsx
  src/components/feature/auth/register/BirthDateSection.tsx
  src/components/feature/auth/register/EmailSection.tsx
  src/components/feature/auth/register/GenderSection.tsx
  src/components/feature/auth/register/NameSection.tsx
  src/components/feature/auth/register/NicknameSection.tsx
  src/components/feature/auth/register/PasswordSection.tsx
  src/components/feature/auth/register/PhoneSection.tsx
  src/constants/urls.ts
Labels: feature

#55 feat: ai 추천 모달에 기능 추가(SCENTLY-127)
  next.config.ts
  src/api/api.ts
  src/api/recommendations/aiRecommendation.ts
  src/app/api/ai-recommendations/route.ts
  src/components/feature/ai-search-modal/AISearchResult.tsx
  src/components/ui/tabs/Tag.tsx
  src/constants/urls.ts
Labels: feature

#54 feat: 찜 목록 컴포넌트 작성 (SCENTLY-130)
  src/app/liked-page/mocks/mockLiked.ts
  src/app/liked-page/page.tsx
  src/app/my-page/page.tsx
  src/components/common/card-component/MainCard.tsx
  src/components/common/review-card/ReviewCard.tsx
  src/types/MainCard.type.ts
Labels: feature

#56 feat: 내가 작성한 리뷰 (SCENTLY-136)
  src/app/detail/[id]/page.tsx
  src/app/liked-page/page.tsx
  src/app/my-page/mocks/mockReviewCard.ts
  src/app/my-page/page.tsx
  src/app/preference-page/page.tsx
  src/app/privacy-page/mocks/userMockData.ts
  src/app/privacy-page/page.tsx
  src/app/review-page/mocks/mockReview.ts
  src/app/review-page/page.tsx
  src/components/common/Footer.tsx
  src/components/common/ReviewlistCard.tsx
  src/components/common/card-component/MainCard.tsx
  src/components/common/review-card/ReviewCard.tsx
  src/components/feature/my-page/MypageCard.tsx
  src/components/feature/preference-page/AIItem.tsx
  src/components/feature/preference-page/PreferenceCard.tsx
  src/components/feature/preference-page/SurveyItem.tsx
  src/components/feature/privacy-page/PrivacyEdit.tsx
  src/components/feature/privacy-page/PrivacyView.tsx
  src/constants/urls.ts
Labels: feature

#60 feat: 상품페이지 라우트 및 API 연결, 무한스크롤 구현(SCENTLY-128)
  src/api/products/productsList.ts
  src/app/api/products/route.ts
  src/app/api/products/search/route.ts
  src/app/detail/[id]/mock/mock.json
  src/app/detail/[id]/page.tsx
  src/app/liked-page/page.tsx
  src/app/my-page/mocks/mockCard.ts
  src/app/my-page/mocks/mockReviewCard.ts
  src/app/my-page/page.tsx
  src/app/products/page.tsx
  src/app/review-page/page.tsx
  src/components/common/CartCard.tsx
  src/components/common/Header.tsx
  src/components/common/ReviewlistCard.tsx
  src/components/common/card-component/MainCard.tsx
  src/components/common/review-card/ReviewCard.tsx
  src/components/feature/ai-search-modal/AISearchResult.tsx
  src/components/feature/detail/DetailSwiper.tsx
  src/components/feature/main/BestReviews.tsx
  src/components/feature/main/PersonalizedProducts.tsx
  src/components/feature/main/PromoBanner.tsx
  src/components/feature/my-page/MypageCard.tsx
  src/components/feature/preference-page/AIItem.tsx
  src/components/feature/preference-page/PreferenceCard.tsx
  src/components/feature/preference-page/SurveyItem.tsx
  src/constants/urls.ts
  src/types/MainCard.type.ts
  src/types/ReviewCard.types.ts
Labels: feature

#61 docs: readme 작성 (SCENTLY-138)
  README.md
Labels: docs

#62 fix: fix bug(SCENTLY-141)
  src/api/products/productsList.ts
  src/app/@modal/(...)ai-search/page.tsx
  src/app/api/products/detail/[id]/route.ts
  src/app/api/products/search/route.ts
  src/app/products/detail/[id]/mock/mock.json
  src/app/products/detail/[id]/page.tsx
  src/components/feature/ai-search-modal/AISearchResult.tsx
Labels: fix
